diff --git a/Makefile b/Makefile
index 3290da2..224bc08 100644
--- a/Makefile
+++ b/Makefile
@@ -17,14 +17,12 @@ INCS_PATH = inc/
 BIN_PATH = bin/
 LIBFT_PATH = libft/
 
-HEADER = $(INCS_PATH)/$(NAME).h
-
-SRCS = main.c pwd.c cd.c execve.c pipe.c hardcoded.c aux_functions.c multiple_pipes.c builtins.c export.c \
-		unset.c fn_list.c fn_main_readline.c fn_mask.c fn_pars.c fn_pip_splt_trim.c fn_vars.c main.c\
+SRCS = fn_list.c fn_main_readline.c fnadd_free.c fnadd_libftmod.c fn_additional.c fn_cleaning.c fn_getenvs.c\
+fn_mask.c fn_pip_splt_trim.c fn_vars.c main.c fn_redirs.c fn_create_data.c\
 
 OBJS = $(SRCS:%.c=bin/%.o)
 CC = gcc
-CFLAGS = -g -O0 #-Wall -Werror -Wextra
+CFLAGS = -g -O0 # -Wall -Werror -Wextra
 LIBFT_FLAGS = -I$(LIBFT_PATH) -L$(LIBFT_PATH) -lft
 LIBRL_FLAGS = -L/usr/local/opt/readline/lib -I/usr/local/opt/readline/include -lreadline
 LIBRL_FLAGS += -L/Users/$(USER)/.brew/opt/readline/lib -I/Users/$(USER)/.brew/opt/readline/include -lreadline
@@ -38,7 +36,7 @@ $(BIN_PATH)%.o: $(SRCS_PATH)%.c
 	@mkdir -p $(BIN_PATH)
 	@$(CC) $(CFLAGS) -I$(LIBFT_PATH) -c $< -o $@
 
-$(NAME): $(OBJS) $(HEADER)
+$(NAME): $(OBJS)
 	@$(MAKE) -C $(LIBFT_PATH) --silent
 	@echo $(PURPLE)"[Creating $(NAME)]"$(NONE)
 	@$(CC) -o $(NAME) $(OBJS) $(LIBFT_FLAGS) $(LIBRL_FLAGS) #-fsanitize=address
@@ -58,8 +56,4 @@ fclean: clean
 re: fclean 
 	@$(MAKE)
 
-run:
-	@$(MAKE)
-	./minishell
-
-.PHONY: all clean fclean re run
+.PHONY: all clean fclean re
